server:
  port: 8300

spring:
  application:
    name: iot-center-auth
  profiles:
    active:
      - server
      - monitor
      - mysql
      - redis
      - feign
      - dev
      - nacos
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    database: 1
  cache:
    redis:
      time-to-live: ${CACHE_REDIS_TIME_TO_LIVE:12H}

logging:
  level:
    com.iot: DEBUG
    com.alibaba.nacos: WARN
  file:
    name: iot/logs/center/auth/${spring.application.name}.log
