spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dc3?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: 192.168.1.2
    port: 5672
  redis:
    host: 192.168.1.2
    port:
  data:
    mongodb:
      host: 192.168.1.2
      port: 27017
  cache:
    redis:
      time-to-live: 5S