server:
  auth:
    build:
      context: ../iot-center/iot-center-auth/
      dockerfile: ./Dockerfile
    image: pnoker/iot-center-auth:1.0.0
    restart: always
    ports:
      - 8300:8300
    environment:
      - NODE_ENV=dev
      - MYSQL_HOST=dc3-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=dc3
      - REDIS_HOST=dc3-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dc3
      - CACHE_REDIS_TIME_TO_LIVE=6H
      - NACOS_HOST=iot-center-register
      - NACOS_PORT=8848
      - SECURITY_USER_NAME=dc3
      - SECURITY_USER_PASSWORD=dc3
    container_name: iot-center-auth
    hostname: iot-center-auth
    volumes:
      - logs:/iot-center/iot-center-auth/iot/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - iot-center-auth