server:
  auth:
    build:
      context: ../iot-center/iot-center-auth/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-center-auth:1.0.0
    restart: always
    ports:
      - 8300:8300
    environment:
      - NODE_ENV=dev
      - MYSQL_HOST=dc3-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=dc3
      - REDIS_HOST=dc3-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dc3
      - CACHE_REDIS_TIME_TO_LIVE=6H
      - EUREKA_HOST=dc3-center-register
      - EUREKA_PORT=8100
      - SECURITY_USER_NAME=dc3
      - SECURITY_USER_PASSWORD=dc3
    container_name: dc3-center-auth
    hostname: dc3-center-auth
    volumes:
      - logs:/dc3-center/dc3-center-auth/dc3/logs
    logging:
      driver: json-file
      options:
        max-size: '20m'
        max-file: '20'
    networks:
      dc3net:
        aliases:
          - dc3-center-auth